# -*- coding: utf-8 -*-

import json
import sys
import tempfile
import unittest
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from engine_adapters import (  # noqa: E402
    EDORIAM_QOL_MARKER_BEGIN,
    EDORIAM_QOL_MARKER_END,
    ENGINE_RPGMAKER_MV,
    ENGINE_RPGMAKER_MZ,
    RPGMAKER_MARKER_BEGIN,
    detect_game,
    install_hook,
    normalize_rpgmaker_text,
    scan_rpgmaker_game,
    uninstall_hook,
)


class RpgMakerAdapterTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        self.bridge = self.root / "source_bridge.js"
        self.bridge.write_text("// bridge\n", encoding="utf-8")
        self.renpy_hook = self.root / "hook.rpy"
        self.renpy_hook.write_text("", encoding="utf-8")

    def tearDown(self):
        self.temp_dir.cleanup()

    def _make_game(self, engine=ENGINE_RPGMAKER_MV, under_www=True):
        game_root = self.root / ("mv" if engine == ENGINE_RPGMAKER_MV else "mz")
        game_root.mkdir()
        exe = game_root / "Game.exe"
        exe.write_bytes(b"")
        content = game_root / "www" if under_www else game_root
        (content / "js" / "plugins").mkdir(parents=True)
        (content / "data").mkdir()
        core = "rpg_core.js" if engine == ENGINE_RPGMAKER_MV else "rmmz_core.js"
        name = "MV" if engine == ENGINE_RPGMAKER_MV else "MZ"
        version = "1.6.1" if name == "MV" else "1.8.1"
        (content / "js" / core).write_text(
            f'Utils.RPGMAKER_NAME = "{name}";\nUtils.RPGMAKER_VERSION = "{version}";\n',
            encoding="utf-8",
        )
        (content / "js" / "plugins.js").write_text(
            '// Generated by RPG Maker.\r\nvar $plugins = [\r\n,];\r\n',
            encoding="utf-8",
            newline="",
        )
        (content / "data" / "System.json").write_text(
            json.dumps({"gameTitle": f"Example {name}"}), encoding="utf-8"
        )
        return exe, content

    def test_detects_mv_www_and_mz_root_layouts(self):
        mv_exe, _ = self._make_game(ENGINE_RPGMAKER_MV, under_www=True)
        mz_exe, _ = self._make_game(ENGINE_RPGMAKER_MZ, under_www=False)

        mv = detect_game(str(mv_exe))
        mz = detect_game(str(mz_exe))

        self.assertEqual(mv.engine, ENGINE_RPGMAKER_MV)
        self.assertEqual(mv.engine_version, "1.6.1")
        self.assertEqual(mv.title, "Example MV")
        self.assertEqual(mz.engine, ENGINE_RPGMAKER_MZ)
        self.assertEqual(mz.engine_version, "1.8.1")
        self.assertNotEqual(mv.cache_id, mz.cache_id)

    def test_install_is_idempotent_and_uninstall_restores_exact_bytes(self):
        exe, content = self._make_game()
        target = detect_game(str(exe))
        plugins_js = content / "js" / "plugins.js"
        original = plugins_js.read_bytes()

        ok, message = install_hook(
            target, str(self.renpy_hook), str(self.bridge), 19876, "session-one"
        )
        self.assertTrue(ok, message)
        self.assertIn(RPGMAKER_MARKER_BEGIN, plugins_js.read_text(encoding="utf-8"))

        ok, message = install_hook(
            target, str(self.renpy_hook), str(self.bridge), 19876, "session-two"
        )
        self.assertTrue(ok, message)
        self.assertEqual(plugins_js.read_text(encoding="utf-8").count(RPGMAKER_MARKER_BEGIN), 1)

        ok, message = uninstall_hook(target)
        self.assertTrue(ok, message)
        self.assertEqual(plugins_js.read_bytes(), original)
        self.assertFalse((content / "js" / "plugins" / "RenpyLensBridge.js").exists())

    def test_install_passes_qol_settings_to_bridge_registration(self):
        exe, content = self._make_game()
        target = detect_game(str(exe))

        ok, message = install_hook(
            target,
            str(self.renpy_hook),
            str(self.bridge),
            19876,
            "qol-session",
            rpgmaker_qol_enabled=True,
            rpgmaker_qol_locale="zh_CN",
            rpgmaker_qol_features={"textSpeed": True, "moveSpeed": False},
        )

        self.assertTrue(ok, message)
        registry = (content / "js" / "plugins.js").read_text(encoding="utf-8")
        self.assertIn('"qolEnabled":"true"', registry)
        self.assertIn('"qolLocale":"zh_CN"', registry)
        self.assertIn('\\"textSpeed\\":true', registry)
        self.assertIn('\\"moveSpeed\\":false', registry)

    def test_install_temporarily_replaces_legacy_qol_and_uninstall_restores_it(self):
        exe, content = self._make_game()
        target = detect_game(str(exe))
        plugins_js = content / "js" / "plugins.js"
        legacy = (
            plugins_js.read_text(encoding="utf-8")
            + f"{EDORIAM_QOL_MARKER_BEGIN}\n"
            + '$plugins.push({"name":"EdoriamQoL","status":true});\n'
            + f"{EDORIAM_QOL_MARKER_END}\n"
        )
        plugins_js.write_text(legacy, encoding="utf-8", newline="")
        original = plugins_js.read_bytes()

        ok, message = install_hook(
            target, str(self.renpy_hook), str(self.bridge), 19876, "session"
        )
        self.assertTrue(ok, message)
        self.assertNotIn(EDORIAM_QOL_MARKER_BEGIN, plugins_js.read_text(encoding="utf-8"))

        ok, message = uninstall_hook(target)
        self.assertTrue(ok, message)
        self.assertEqual(plugins_js.read_bytes(), original)

    def test_uninstall_preserves_external_plugin_registry_changes(self):
        exe, content = self._make_game()
        target = detect_game(str(exe))
        plugins_js = content / "js" / "plugins.js"
        ok, message = install_hook(
            target, str(self.renpy_hook), str(self.bridge), 19876, "session"
        )
        self.assertTrue(ok, message)
        with plugins_js.open("a", encoding="utf-8") as handle:
            handle.write("// user change\n")

        ok, message = uninstall_hook(target)

        self.assertTrue(ok, message)
        restored = plugins_js.read_text(encoding="utf-8")
        self.assertNotIn(RPGMAKER_MARKER_BEGIN, restored)
        self.assertIn("// user change", restored)

    def test_offline_scan_extracts_dialogue_speakers_choices_and_scroll_text(self):
        exe, content = self._make_game(ENGINE_RPGMAKER_MZ, under_www=False)
        actors = [None, {"id": 1, "name": "Alice"}]
        (content / "data" / "Actors.json").write_text(json.dumps(actors), encoding="utf-8")
        event_list = [
            {"code": 101, "parameters": ["", 0, 0, 2, "Narrator"]},
            {"code": 401, "parameters": ["Hello \\V[3]"]},
            {"code": 401, "parameters": ["second line"]},
            {"code": 102, "parameters": [["Yes", "No"], 0, 0, 2, 0]},
            {"code": 105, "parameters": [2, False]},
            {"code": 405, "parameters": ["Scrolling \\C[2]text\\C[0]"]},
            {"code": 0, "parameters": []},
        ]
        map_data = {
            "events": [None, {"pages": [{"list": event_list}]}],
        }
        (content / "data" / "Map001.json").write_text(json.dumps(map_data), encoding="utf-8")
        (content / "data" / "CommonEvents.json").write_text("[null]", encoding="utf-8")
        (content / "data" / "Troops.json").write_text("[null]", encoding="utf-8")

        entries = scan_rpgmaker_game(detect_game(str(exe)))
        by_source = {entry["source"]: entry for entry in entries}

        self.assertIn("Hello ⟦RL_V_3⟧\nsecond line", by_source)
        self.assertEqual(by_source["Hello ⟦RL_V_3⟧\nsecond line"]["speaker"], "Narrator")
        self.assertEqual(by_source["Yes"]["entry_type"], "choice")
        self.assertIn("Scrolling text", by_source)

    def test_normalize_preserves_dynamic_tokens_and_removes_formatting(self):
        value = normalize_rpgmaker_text(r"\C[2]Gold: \V[1] \SE[hero]\G")
        self.assertEqual(value, "Gold: ⟦RL_V_1⟧ ⟦RL_G⟧")


if __name__ == "__main__":
    unittest.main()
